### ISSUE TITLE
Sync-Settings: No Location Service

### ISSUE THREAD

**Issue by C00kie-** [UziTech/sync-settings-git-location#57]
Hello, I installed the packages as follow in your instructions, but atom tells that there is no another backup location installed. 

> 

    Install Sync-Settings.
    Install Sync-Settings-git-location.
    Go To the Sync-Settings settings page.
    Check Use Other Backup Location.
    Create a new repository. We recommend making it private.
    Enter the url in the Git URL setting on the sync-settings-git-location settings page
    Run command sync-settings:backup to backup your settings.

Installed packages:
sync-settings
sync-settings-git-local

all configurations done (github repo set up, check the case "other location")

I got an error message:
"You have selected to use an other backup location but none are installed."

Thanks

**Comment by UziTech** [comment]
What version of Atom are you using? Have you tried restarting Atom?

**Comment by C00kie-** [comment]
Thanks for the quick reply. :) 
I'm using Atom 1.50.0

Actually after restarting atom, it's showing another error message: 
> Command failed: git clone --depth 1 http://github.com/C00kie-/atom-config.git .
Cloning into '.'...
fatal: could not read Username for 'https://github.com': No such device or address

I think the error talks by itself ;) thanks !
